name: External Libraries Results

on:
  workflow_run:
    workflows: [External Libraries Test]
    types:
      - completed

  workflow_dispatch:
env:
  # It's convenient to set variables for values used multiple times in the workflow
  SKETCHES_REPORTS_PATH: artifacts/libraries-report
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PR_EVENT_PATH: artifacts/event-file/event.json

jobs:
  lib-test-results:
    name: External Libraries Test Results
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download and Extract Artifacts
        run: |
          mkdir -p artifacts && cd artifacts
          mkdir -p libraries-report
          mkdir -p event-file
          artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -j "$name.zip" -d "temp_$name"
            if [[ "$name" == "Event File" ]]; then
              mv "temp_$name"/* event-file
            else
              mv "temp_$name"/* libraries-report
            fi
            rm -r "temp_$name"
            if [[ "$name" == "event.json" ]]; then
              mkdir -p artifacts/Event\ file
              mv libraries-report/event.json /Event\ file/
            fi
          done
          echo "Contents of parent directory:"
          ls -R ..
    
      - name: Report results
        uses: P-R-O-C-H-Y/report-size-deltas@libs
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
          github-token: ${{ env.GITHUB_TOKEN }}
          pr-event-path: ${{ env.PR_EVENT_PATH }}
