name: Sizes Test
# Comment

# The workflow will run labeled pull requests
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

env:
  # It's convenient to set variables for values used multiple times in the workflow
  SKETCHES_REPORTS_PATH: sizes-report
  SKETCHES_REPORTS_ARTIFACT_NAME: sizes-report
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  compile-sketch:
    if: |
      contains(github.event.pull_request.labels.*.name, 'sizes_test')
    runs-on: ubuntu-latest

    env:
      REPOSITORY: |
        - source-path: '.'
          name: "espressif:esp32"

    strategy:
      matrix:
        target:
          - esp32
          - esp32s2
          - esp32c3
          - esp32s3
          - esp32c6
          - esp32h2

        include:
          - target: esp32
            fqbn: espressif:esp32:esp32
          - target: esp32s2
            fqbn: espressif:esp32:esp32s2
          - target: esp32c3
            fqbn: espressif:esp32:esp32c3
          - target: esp32s3
            fqbn: espressif:esp32:esp32s3
          - target: esp32c6
            fqbn: espressif:esp32:esp32c6
          - target: esp32h2
            fqbn: espressif:esp32:esp32h2


    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: P-R-O-C-H-Y/compile-sketches@sizes
        with:
          platforms: |
            ${{ env.REPOSITORY }}
          target: ${{ matrix.target }}
          fqbn: ${{ matrix.fqbn }}
          # The path to the libraries folder TODO: Change this to the correct path
          sketch-paths: |
            - libraries/SD/
            - libraries/ESP_SR/
          use-json-file: false
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          enable-warnings-report: false
          cli-compile-flags: |
            - --warnings="all"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}-${{ matrix.target }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

  event_file:
    name: "Event File"
    if: |
      contains(github.event.pull_request.labels.*.name, 'sizes_test')
    needs: compile-sketch
    runs-on: ubuntu-latest
    steps:
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: Event File
           path: ${{github.event_path}}